add: iterator support and yarn.lock to .gitignore
supercharge/promise-pool pull request #36
Opened 2021-09-23 16:59 UTC by WildEgo

Pretty much as the title says added iterator support and added yarn.lock to the .gitignore.

Result of examples/promise-pool.js
```
1 waited 200ms
0 waited 800ms
3 waited 100ms
2 waited 700ms
4 waited 400ms
6 waited 600ms
5 waited 1000ms
7 waited 500ms
9 waited 300ms
8 waited 900ms
Results ->
[
  [ 200, '1' ],  [ 800, '0' ],
  [ 100, '3' ],  [ 700, '2' ],
  [ 400, '4' ],  [ 600, '6' ],
  [ 1000, '5' ], [ 500, '7' ],
  [ 300, '9' ],  [ 900, '8' ]
]
Errors -> none
```

Test results (Basically the same as the original):
```
--------------------------|---------|----------|---------|---------|-------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------------|---------|----------|---------|---------|-------------------
All files                 |     100 |      100 |   96.55 |     100 | 
 index.js                 |     100 |      100 |     100 |     100 | 
 promise-pool-error.js    |     100 |      100 |     100 |     100 | 
 promise-pool-executor.js |     100 |      100 |   94.73 |     100 | 
 promise-pool.js          |     100 |      100 |     100 |     100 | 
--------------------------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       1 failed, 20 passed, 21 total
Snapshots:   0 total
Time:        2.139 s, estimated 4 s
Ran all test suites.
```

2021-09-23 18:06 UTC, marcuspoehls requested changes
Can you please add a test for the index? Maybe there's a related test already that can be extended.

If you don't know how to test that I can add that later. It's not a requirement to get this PR merged.

2021-09-23 18:06 UTC, marcuspoehls commented on src/promise-pool-executor.ts
> +    for (const [i, item] of Object.entries(this.items)) {
Object.entries is giving the key as a string. Let's use the Array.entries method (`this.items.entries()`) to provide the index as an integer.

2021-09-23 18:08 UTC, marcuspoehls commented
In the PR description is a failing test. Maybe you can check what's failing?

2021-09-23 18:11 UTC, WildEgo commented
> In the PR description is a failing test. Maybe you can check what's failing?

The failing test was already failing before, it's one of the integers that seems out of place, I don't know where it comes exactly since I'm not too familiar with the project's code

2021-09-23 18:23 UTC, marcuspoehls commented
Seems to be Sa flaky test. Maybe the test itself ist not good designed and requires some refinements. You can leave the test as it is. Thank you for digging down!

2021-09-23 18:24 UTC, WildEgo commented
> Seems to be a flaky test. Maybe the test itself ist not good designed and requires some refinements. You can leave the test as it is. Thank you for digging down!

No problem, always happy to help who's helping me.

2021-09-24 09:28 UTC, merged

2021-09-24 09:29 UTC, marcuspoehls commented
Merged! Thank you Luis for your time and work! ❤️